version: '3'
services:
    frontend:
        stdin_open: true
        tty: true
        build: .
        ports:
            - '3000:3000'
        environment: 
            - REACT_APP_BACKEND_URL=http://139.162.143.213:8000